title: Sylvain DECOUT
subtitle: Tech Lead / Architect / Developer
name: Sylvain Decout
email: sylvain.decout@shodo.io
description: >-
  Sylvain DECOUT (Tech Lead / Architect / Developer)
baseurl: ""
url: "https://sylvaindecout.github.io"

# GitHub repository
github_username: sylvaindecout
repository: "sylvaindecout/sylvaindecout.github.io"

# Personal information
author:
  name: "Sylvain Decout"
  avatar: "/assets/images/me.png"
  bio: Dev at Shodo
  location: "Paris, France"
  links:
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: "https://www.linkedin.com/in/sylvain-decout"
    - label: "GitHub"
      icon: fab fa-fw fa-github
      url: "https://github.com/sylvaindecout"
    - label: Twitter
      icon: fab fa-fw fa-twitter-square
      url: "https://twitter.com/sylvaindecout"
    - label: Instagram
      icon: fab fa-fw fa-instagram
      url: "https://instagram.com/sylvain.decout"
twitter:
  username: sylvaindecout
social:
  name: Sylvain Decout
  links:
    - "https://twitter.com/sylvaindecout"
    - "https://www.linkedin.com/in/sylvain-decout"
    - "https://instagram.com/sylvain.decout"
footer:
  links:
    - label: "GitHub"
      icon: fab fa-fw fa-github
      url: "https://github.com/sylvaindecout"
    - label: LinkedIn
      icon: fab fa-fw fa-linkedin
      url: "https://www.linkedin.com/in/sylvain-decout"

# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"
locale: "en-US"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Layout
include: ["_pages"]
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
atom_feed:
  hide: true